2018-03-27 20:58:50,979 ERROR 2308 nodejs.ClusterClientNoResponseError: client no response in 615507ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/preview/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2308
hostname: lifudeMacBook-Pro.local

2018-03-27 21:25:27,125 ERROR 2548 [-/::1/-/2ms GET /list/%7Bitem.images.small%7D] nodejs.TypeError: Cannot read property 'subjects' of undefined
    at HomeController.list (/Users/rich/project/preview/app/controller/home.js:13:43)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 2548
hostname: lifudeMacBook-Pro.local

2018-03-27 21:50:19,054 ERROR 2672 [-/::1/-/2962ms GET /list/1] nodejs.Template render error: expected variable end
    at Object._prettifyError (/Users/rich/project/preview/node_modules/nunjucks/src/lib.js:35:11)
    at Template.render (/Users/rich/project/preview/node_modules/nunjucks/src/environment.js:526:21)
    at /Users/rich/project/preview/node_modules/nunjucks/src/environment.js:350:27
    at createTemplate (/Users/rich/project/preview/node_modules/nunjucks/src/environment.js:299:9)
    at handle (/Users/rich/project/preview/node_modules/nunjucks/src/environment.js:311:11)
    at /Users/rich/project/preview/node_modules/nunjucks/src/environment.js:323:9
    at next (/Users/rich/project/preview/node_modules/nunjucks/src/lib.js:281:7)
    at Object.asyncIter (/Users/rich/project/preview/node_modules/nunjucks/src/lib.js:287:3)
    at NunjucksEnvironment.getTemplate (/Users/rich/project/preview/node_modules/nunjucks/src/environment.js:305:9)
    at NunjucksEnvironment.render (/Users/rich/project/preview/node_modules/nunjucks/src/environment.js:344:10)
    at Promise (/Users/rich/project/preview/node_modules/egg-view-nunjucks/lib/view.js:13:25)
    at new Promise (<anonymous>)
    at NunjucksView.render (/Users/rich/project/preview/node_modules/egg-view-nunjucks/lib/view.js:12:12)
    at ContextView.[contextView#render] (/Users/rich/project/preview/node_modules/egg-view/lib/context_view.js:70:23)
    at <anonymous>
name: 'Template render error'
pid: 2672
hostname: lifudeMacBook-Pro.local

2018-03-27 21:50:30,774 ERROR 2672 [-/::1/-/1920ms GET /list/1] nodejs.Template render error: expected variable end
    at Object._prettifyError (/Users/rich/project/preview/node_modules/nunjucks/src/lib.js:35:11)
    at Template.render (/Users/rich/project/preview/node_modules/nunjucks/src/environment.js:526:21)
    at /Users/rich/project/preview/node_modules/nunjucks/src/environment.js:350:27
    at createTemplate (/Users/rich/project/preview/node_modules/nunjucks/src/environment.js:299:9)
    at handle (/Users/rich/project/preview/node_modules/nunjucks/src/environment.js:311:11)
    at /Users/rich/project/preview/node_modules/nunjucks/src/environment.js:323:9
    at next (/Users/rich/project/preview/node_modules/nunjucks/src/lib.js:281:7)
    at Object.asyncIter (/Users/rich/project/preview/node_modules/nunjucks/src/lib.js:287:3)
    at NunjucksEnvironment.getTemplate (/Users/rich/project/preview/node_modules/nunjucks/src/environment.js:305:9)
    at NunjucksEnvironment.render (/Users/rich/project/preview/node_modules/nunjucks/src/environment.js:344:10)
    at Promise (/Users/rich/project/preview/node_modules/egg-view-nunjucks/lib/view.js:13:25)
    at new Promise (<anonymous>)
    at NunjucksView.render (/Users/rich/project/preview/node_modules/egg-view-nunjucks/lib/view.js:12:12)
    at ContextView.[contextView#render] (/Users/rich/project/preview/node_modules/egg-view/lib/context_view.js:70:23)
    at <anonymous>
name: 'Template render error'
pid: 2672
hostname: lifudeMacBook-Pro.local

2018-03-28 19:53:56,618 ERROR 622 nodejs.ClusterClientNoResponseError: client no response in 188580ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/preview/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 622
hostname: lifudeMacBook-Pro.local

2018-03-28 20:00:56,289 ERROR 900 [-/127.0.0.1/-/1ms GET /] nodejs.ReferenceError: puppeteer is not defined
    at CrawlerService.crawlerVideo (/Users/rich/project/preview/app/service/crawler.js:13:21)
    at ctx.runInBackground (/Users/rich/project/preview/app.js:8:51)
    at Object.runInBackground (/Users/rich/project/preview/node_modules/egg/app/extend/context.js:203:35)
    at Messenger.app.messenger.on.data (/Users/rich/project/preview/app.js:7:13)
    at emitOne (events.js:116:13)
    at Messenger.emit (events.js:211:7)
    at Messenger._onMessage (/Users/rich/project/preview/node_modules/egg/lib/core/messenger.js:116:12)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

pid: 900
hostname: lifudeMacBook-Pro.local

2018-03-28 20:03:23,766 ERROR 961 [-/127.0.0.1/-/8730ms GET /] nodejs.ReferenceError: doubanId is not defined
    at CrawlerService.crawlerVideo (/Users/rich/project/preview/app/service/crawler.js:64:7)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 961
hostname: lifudeMacBook-Pro.local

2018-03-28 20:03:35,468 ERROR 961 [-/127.0.0.1/-/8198ms GET /] nodejs.ReferenceError: doubanId is not defined
    at CrawlerService.crawlerVideo (/Users/rich/project/preview/app/service/crawler.js:64:7)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 961
hostname: lifudeMacBook-Pro.local

2018-03-28 20:51:38,172 ERROR 1607 [-/::1/-/18ms GET /detail/3445906] nodejs.TypeError: Cannot read property 'medium' of undefined
    at HomeService.fetchDetail (/Users/rich/project/preview/app/service/home.js:58:90)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 1607
hostname: lifudeMacBook-Pro.local

2018-03-28 20:52:23,391 ERROR 1639 [-/::1/-/18ms GET /detail/3445906] nodejs.TypeError: Cannot read property 'medium' of undefined
    at HomeService.fetchDetail (/Users/rich/project/preview/app/service/home.js:58:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 1639
hostname: lifudeMacBook-Pro.local

2018-03-28 21:08:25,483 ERROR 2033 [-/127.0.0.1/-/6791ms GET /] nodejs.ReferenceError: movie is not defined
    at ctx.runInBackground (/Users/rich/project/preview/app.js:11:17)
    at <anonymous>

pid: 2033
hostname: lifudeMacBook-Pro.local

2018-03-28 21:23:37,972 ERROR 2368 [-/127.0.0.1/-/11467ms GET /] nodejs.TypeError: Cannot read property 'list' of undefined
    at ctx.runInBackground (/Users/rich/project/preview/app.js:11:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 2368
hostname: lifudeMacBook-Pro.local

2018-03-28 21:30:02,340 ERROR 2487 [-/127.0.0.1/-/7201ms GET /] nodejs.TypeError: Cannot set property 'video' of undefined
    at ctx.runInBackground (/Users/rich/project/preview/app.js:9:25)
    at <anonymous>

pid: 2487
hostname: lifudeMacBook-Pro.local

2018-03-28 21:36:48,014 ERROR 2581 [-/127.0.0.1/-/7140ms GET /] nodejs.TypeError: Cannot set property 'video' of undefined
    at ctx.runInBackground (/Users/rich/project/preview/app.js:10:25)
    at <anonymous>

pid: 2581
hostname: lifudeMacBook-Pro.local

2018-03-28 21:37:34,264 ERROR 2608 [-/127.0.0.1/-/7630ms GET /] nodejs.TypeError: Cannot set property 'video' of undefined
    at ctx.runInBackground (/Users/rich/project/preview/app.js:10:25)
    at <anonymous>

pid: 2608
hostname: lifudeMacBook-Pro.local

2018-03-28 21:43:29,375 ERROR 2797 [-/::1/-/230ms GET /detail/30152451] nodejs.TypeError: Cannot read property 'id' of undefined
    at HomeService.fetchDetail (/Users/rich/project/preview/app/service/home.js:52:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 2797
hostname: lifudeMacBook-Pro.local

2018-03-28 21:43:41,859 ERROR 2797 [-/::1/-/9263ms GET /detail/30152451] nodejs.TypeError: Cannot read property 'id' of undefined
    at HomeService.fetchDetail (/Users/rich/project/preview/app/service/home.js:52:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 2797
hostname: lifudeMacBook-Pro.local

2018-03-28 21:43:57,645 ERROR 2797 [-/127.0.0.1/-/30246ms GET /] nodejs.Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/Users/rich/project/preview/node_modules/puppeteer/lib/NavigatorWatcher.js:71:21)
    at <anonymous>

pid: 2797
hostname: lifudeMacBook-Pro.local

2018-03-28 21:44:44,990 ERROR 2840 [-/::1/-/3522ms GET /detail/30152451] nodejs.TypeError: Cannot read property 'id' of undefined
    at HomeService.fetchDetail (/Users/rich/project/preview/app/service/home.js:52:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 2840
hostname: lifudeMacBook-Pro.local

2018-03-28 21:50:12,979 ERROR 2999 [-/127.0.0.1/-/16661ms GET /] nodejs.TypeError: Cannot set property 'video' of undefined
    at ctx.runInBackground (/Users/rich/project/preview/app.js:9:25)
    at <anonymous>

pid: 2999
hostname: lifudeMacBook-Pro.local

2018-03-28 21:54:31,676 ERROR 3111 [-/127.0.0.1/-/30251ms GET /] nodejs.Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/Users/rich/project/preview/node_modules/puppeteer/lib/NavigatorWatcher.js:71:21)
    at <anonymous>

pid: 3111
hostname: lifudeMacBook-Pro.local

2018-04-09 21:04:05,797 ERROR 1109 [-/::1/-/7ms GET /api/search?q=%E6%9D%8E%E5%AE%89] nodejs.TypeError: Cannot read property 'fetchSearch' of undefined
    at MovieController.search (/Users/rich/project/preview/app/controller/movie.js:9:32)
    at Object.callFn (/Users/rich/project/preview/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/rich/project/preview/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/rich/project/preview/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/rich/project/preview/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/rich/project/preview/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/rich/project/preview/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/rich/project/preview/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/rich/project/preview/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/rich/project/preview/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/rich/project/preview/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/Users/rich/project/preview/node_modules/koa-compose/index.js:42:32)
    at next (/Users/rich/project/preview/node_modules/koa-compose/index.js:43:18)
    at errorHandler (/Users/rich/project/preview/app/middleware/error_handler.js:4:13)
    at dispatch (/Users/rich/project/preview/node_modules/koa-compose/index.js:42:32)
    at next (/Users/rich/project/preview/node_modules/koa-compose/index.js:43:18)

pid: 1109
hostname: lifudeMacBook-Pro.local

2018-04-09 21:04:49,538 ERROR 1133 [-/::1/-/7ms GET /api/search?q=%E6%9D%8E%E5%AE%89] nodejs.TypeError: qs is not a function
    at HomeService.fetchSearch (/Users/rich/project/preview/app/service/home.js:92:19)
    at MovieController.search (/Users/rich/project/preview/app/controller/movie.js:9:40)
    at Object.callFn (/Users/rich/project/preview/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/rich/project/preview/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/rich/project/preview/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/rich/project/preview/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/rich/project/preview/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/rich/project/preview/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/rich/project/preview/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/rich/project/preview/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/rich/project/preview/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/rich/project/preview/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/Users/rich/project/preview/node_modules/koa-compose/index.js:42:32)
    at next (/Users/rich/project/preview/node_modules/koa-compose/index.js:43:18)
    at errorHandler (/Users/rich/project/preview/app/middleware/error_handler.js:4:13)
    at dispatch (/Users/rich/project/preview/node_modules/koa-compose/index.js:42:32)

pid: 1133
hostname: lifudeMacBook-Pro.local

2018-05-20 14:24:02,664 ERROR 1467 [-/127.0.0.1/-/7ms GET /] nodejs.ReferenceError: movie is not defined
    at HomeController.index (/Users/rich/project/weiwei/app/controller/home.js:7:36)
    at Object.callFn (/Users/rich/project/weiwei/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/rich/project/weiwei/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/rich/project/weiwei/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/rich/project/weiwei/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/rich/project/weiwei/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/rich/project/weiwei/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/rich/project/weiwei/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/rich/project/weiwei/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/rich/project/weiwei/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/rich/project/weiwei/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/Users/rich/project/weiwei/node_modules/koa-compose/index.js:42:32)
    at next (/Users/rich/project/weiwei/node_modules/koa-compose/index.js:43:18)
    at errorHandler (/Users/rich/project/weiwei/app/middleware/error_handler.js:4:13)
    at dispatch (/Users/rich/project/weiwei/node_modules/koa-compose/index.js:42:32)
    at next (/Users/rich/project/weiwei/node_modules/koa-compose/index.js:43:18)

pid: 1467
hostname: lifudeMacBook-Pro.local

2018-05-20 14:30:07,708 ERROR 1485 [-/::1/-/2ms GET /admin] nodejs.AssertionError [ERR_ASSERTION]: Can't find admin.html from /Users/rich/project/weiwei/app/view
    at Map.resolve (/Users/rich/project/weiwei/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
generatedMessage: false
name: 'AssertionError [ERR_ASSERTION]'
code: 'ERR_ASSERTION'
actual: undefined
expected: true
operator: '=='
pid: 1485
hostname: lifudeMacBook-Pro.local

2018-05-20 15:35:48,416 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 243213ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 15:45:33,157 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 584655ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 15:56:19,855 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 626574ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 16:11:06,215 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 866309ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 16:21:04,406 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578151ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 16:30:04,748 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 520301ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 16:40:04,289 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 579503ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 16:50:03,267 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578953ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 17:00:02,509 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 579224ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 17:10:01,262 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578732ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 17:19:59,933 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578643ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 17:29:57,317 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 577357ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 17:39:56,005 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578653ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 17:49:55,790 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 579759ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 17:59:54,353 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578542ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 18:09:52,687 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578315ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 18:19:51,471 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578757ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 18:29:49,267 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 577765ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 18:39:48,053 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578748ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 18:49:45,853 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 577751ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 18:59:43,601 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 577695ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 19:09:42,454 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578805ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 19:18:41,264 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 518759ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 19:28:39,670 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578358ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 19:38:38,299 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578582ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 19:53:22,902 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 864519ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 20:03:21,496 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578534ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 20:13:20,080 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578533ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 20:23:17,726 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 577587ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 20:33:16,345 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578565ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 20:43:15,068 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578667ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 20:53:13,591 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578466ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 21:03:12,190 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578537ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 21:08:40,809 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 308570ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 21:18:39,472 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578604ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 21:28:37,913 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578376ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 21:38:35,513 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 577544ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 21:48:34,308 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578732ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 21:58:32,896 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578523ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 22:08:31,312 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578368ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 22:18:28,900 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 577526ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 22:28:27,351 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578397ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 22:38:26,078 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 578674ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 22:48:22,272 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 576160ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 22:58:17,900 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 575613ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 23:08:13,636 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 575723ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 23:18:10,330 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 576687ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 23:28:06,031 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 575690ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-20 23:37:42,605 ERROR 2100 nodejs.ClusterClientNoResponseError: client no response in 576570ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/rich/project/weiwei/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 2100
hostname: lifudeMacBook-Pro.local

2018-05-21 09:23:05,949 ERROR 9232 nodejs.unhandledExceptionError: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TCP.onread (net.js:606:25)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 9232
hostname: DELL-PC

2018-05-21 09:43:57,454 ERROR 6832 [-/127.0.0.1/-/3ms POST /updateImg] nodejs.ReferenceError: req is not defined
    at HomeController.updateImg (E:\Rich2017\2018\project\weiwei\app\controller\home.js:23:16)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at Object.classControllerMiddleware (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at wrappedController (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)
    at errorHandler (E:\Rich2017\2018\project\weiwei\app\middleware\error_handler.js:4:13)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)

pid: 6832
hostname: DELL-PC

2018-05-21 09:44:47,604 ERROR 11444 [-/127.0.0.1/-/3ms POST /updateImg] nodejs.TypeError: Cannot read property 'headers' of undefined
    at IncomingForm.parse (E:\Rich2017\2018\project\weiwei\node_modules\formidable\lib\incoming_form.js:112:24)
    at HomeController.updateImg (E:\Rich2017\2018\project\weiwei\app\controller\home.js:24:10)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at Object.classControllerMiddleware (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at wrappedController (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)
    at errorHandler (E:\Rich2017\2018\project\weiwei\app\middleware\error_handler.js:4:13)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)

pid: 11444
hostname: DELL-PC

2018-05-21 10:56:42,598 ERROR 14024 nodejs.unhandledExceptionError: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TCP.onread (net.js:606:25)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 14024
hostname: DELL-PC

2018-05-21 11:00:21,523 ERROR 14024 nodejs.unhandledExceptionError: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TCP.onread (net.js:606:25)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 14024
hostname: DELL-PC

2018-05-21 11:03:50,188 ERROR 6296 nodejs.unhandledExceptionError: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TCP.onread (net.js:606:25)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 6296
hostname: DELL-PC

2018-05-21 11:05:31,105 ERROR 6772 nodejs.TypeError: Cannot read property 'config' of undefined (uncaughtException throw 1 times on pid:6772)
    at uploadToQiniu (E:\Rich2017\2018\project\weiwei\app\service\qiniu.js:36:25)
    at form (E:\Rich2017\2018\project\weiwei\app\controller\home.js:26:9)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-formidable\index.js:26:7
    at IncomingForm.<anonymous> (E:\Rich2017\2018\project\weiwei\node_modules\formidable\lib\incoming_form.js:107:9)
    at emitNone (events.js:105:13)
    at IncomingForm.emit (events.js:207:7)
    at IncomingForm._maybeEnd (E:\Rich2017\2018\project\weiwei\node_modules\formidable\lib\incoming_form.js:557:8)
    at E:\Rich2017\2018\project\weiwei\node_modules\formidable\lib\incoming_form.js:238:12
    at WriteStream.<anonymous> (E:\Rich2017\2018\project\weiwei\node_modules\formidable\lib\file.js:79:5)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at WriteStream.emit (events.js:207:7)
    at finishMaybe (_stream_writable.js:603:14)
    at afterWrite (_stream_writable.js:455:3)
    at onwrite (_stream_writable.js:445:7)
    at fs.js:2189:5

pid: 6772
hostname: DELL-PC

2018-05-21 11:09:59,033 ERROR 8316 nodejs.unhandledRejectionError: [object Object]
    at Application._unhandledRejectionHandler (E:\Rich2017\2018\project\weiwei\node_modules\egg\lib\egg.js:302:24)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:94:22)
    at process._tickCallback (internal/process/next_tick.js:189:7)
name: 'unhandledRejectionError'
pid: 8316
hostname: DELL-PC

2018-05-21 11:14:16,214 ERROR 10216 nodejs.unhandledRejectionError: [object Object]
    at Application._unhandledRejectionHandler (E:\Rich2017\2018\project\weiwei\node_modules\egg\lib\egg.js:302:24)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:94:22)
    at process._tickCallback (internal/process/next_tick.js:189:7)
name: 'unhandledRejectionError'
pid: 10216
hostname: DELL-PC

2018-05-21 11:22:34,800 ERROR 8760 [-/127.0.0.1/-/4ms POST /updateImg] nodejs.TypeError: Cannot read property 'digest' of undefined
    at new QiniuService (E:\Rich2017\2018\project\weiwei\app\service\qiniu.js:8:34)
    at getInstance (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\loader\context_loader.js:92:18)
    at ClassLoader.get (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\loader\context_loader.js:27:22)
    at HomeController.updateImg (E:\Rich2017\2018\project\weiwei\app\controller\home.js:23:22)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at Object.classControllerMiddleware (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at wrappedController (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)

pid: 8760
hostname: DELL-PC

2018-05-21 11:32:10,891 ERROR 8916 nodejs.unhandledRejectionError: [object Object]
    at Application._unhandledRejectionHandler (E:\Rich2017\2018\project\weiwei\node_modules\egg\lib\egg.js:302:24)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:94:22)
    at process._tickCallback (internal/process/next_tick.js:189:7)
name: 'unhandledRejectionError'
pid: 8916
hostname: DELL-PC

2018-05-21 14:37:07,739 ERROR 10216 nodejs.unhandledExceptionError: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TCP.onread (net.js:606:25)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 10216
hostname: DELL-PC

2018-05-21 14:42:02,905 ERROR 11036 [-/127.0.0.1/-/7ms POST /updateImg] nodejs.ReferenceError: formUploader is not defined
    at QiniuService.getLoadConf (E:\Rich2017\2018\project\weiwei\app\service\qiniu.js:42:13)
    at new QiniuService (E:\Rich2017\2018\project\weiwei\app\service\qiniu.js:9:28)
    at getInstance (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\loader\context_loader.js:92:18)
    at ClassLoader.get (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\loader\context_loader.js:27:22)
    at HomeController.updateImg (E:\Rich2017\2018\project\weiwei\app\controller\home.js:23:22)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at Object.classControllerMiddleware (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at wrappedController (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)

pid: 11036
hostname: DELL-PC

2018-05-21 14:43:36,939 ERROR 9300 nodejs.ReferenceError: tokenTimeOut is not defined
    at QiniuService.uploadToQiniu (E:\Rich2017\2018\project\weiwei\app\service\qiniu.js:50:9)
    at form (E:\Rich2017\2018\project\weiwei\app\service\qiniu.js:76:36)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-formidable\index.js:26:7
    at IncomingForm.<anonymous> (E:\Rich2017\2018\project\weiwei\node_modules\formidable\lib\incoming_form.js:107:9)
    at emitNone (events.js:105:13)
    at IncomingForm.emit (events.js:207:7)
    at IncomingForm._maybeEnd (E:\Rich2017\2018\project\weiwei\node_modules\formidable\lib\incoming_form.js:557:8)
    at E:\Rich2017\2018\project\weiwei\node_modules\formidable\lib\incoming_form.js:238:12
    at WriteStream.<anonymous> (E:\Rich2017\2018\project\weiwei\node_modules\formidable\lib\file.js:79:5)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at WriteStream.emit (events.js:207:7)
    at finishMaybe (_stream_writable.js:603:14)
    at afterWrite (_stream_writable.js:455:3)
    at onwrite (_stream_writable.js:445:7)
    at fs.js:2189:5

pid: 9300
hostname: DELL-PC

2018-05-21 14:44:00,030 ERROR 15796 nodejs.ReferenceError: ctx is not defined
    at QiniuService.tokenTimeOut (E:\Rich2017\2018\project\weiwei\app\service\qiniu.js:31:9)
    at QiniuService.uploadToQiniu (E:\Rich2017\2018\project\weiwei\app\service\qiniu.js:50:14)
    at form (E:\Rich2017\2018\project\weiwei\app\service\qiniu.js:76:36)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-formidable\index.js:26:7
    at IncomingForm.<anonymous> (E:\Rich2017\2018\project\weiwei\node_modules\formidable\lib\incoming_form.js:107:9)
    at emitNone (events.js:105:13)
    at IncomingForm.emit (events.js:207:7)
    at IncomingForm._maybeEnd (E:\Rich2017\2018\project\weiwei\node_modules\formidable\lib\incoming_form.js:557:8)
    at E:\Rich2017\2018\project\weiwei\node_modules\formidable\lib\incoming_form.js:238:12
    at WriteStream.<anonymous> (E:\Rich2017\2018\project\weiwei\node_modules\formidable\lib\file.js:79:5)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at WriteStream.emit (events.js:207:7)
    at finishMaybe (_stream_writable.js:603:14)
    at afterWrite (_stream_writable.js:455:3)
    at onwrite (_stream_writable.js:445:7)

pid: 15796
hostname: DELL-PC

2018-05-21 14:44:43,913 ERROR 10964 nodejs.ReferenceError: config is not defined
    at QiniuService.getToken (E:\Rich2017\2018\project\weiwei\app\service\qiniu.js:20:36)
    at QiniuService.tokenTimeOut (E:\Rich2017\2018\project\weiwei\app\service\qiniu.js:35:31)
    at QiniuService.uploadToQiniu (E:\Rich2017\2018\project\weiwei\app\service\qiniu.js:51:14)
    at form (E:\Rich2017\2018\project\weiwei\app\service\qiniu.js:77:36)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-formidable\index.js:26:7
    at IncomingForm.<anonymous> (E:\Rich2017\2018\project\weiwei\node_modules\formidable\lib\incoming_form.js:107:9)
    at emitNone (events.js:105:13)
    at IncomingForm.emit (events.js:207:7)
    at IncomingForm._maybeEnd (E:\Rich2017\2018\project\weiwei\node_modules\formidable\lib\incoming_form.js:557:8)
    at E:\Rich2017\2018\project\weiwei\node_modules\formidable\lib\incoming_form.js:238:12
    at WriteStream.<anonymous> (E:\Rich2017\2018\project\weiwei\node_modules\formidable\lib\file.js:79:5)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at WriteStream.emit (events.js:207:7)
    at finishMaybe (_stream_writable.js:603:14)
    at afterWrite (_stream_writable.js:455:3)

pid: 10964
hostname: DELL-PC

2018-05-21 14:45:23,195 ERROR 12000 nodejs.unhandledRejectionError: [object Object]
    at Application._unhandledRejectionHandler (E:\Rich2017\2018\project\weiwei\node_modules\egg\lib\egg.js:302:24)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:94:22)
    at process._tickCallback (internal/process/next_tick.js:189:7)
name: 'unhandledRejectionError'
pid: 12000
hostname: DELL-PC

2018-05-21 14:46:48,261 ERROR 15812 nodejs.unhandledRejectionError: [object Object]
    at Application._unhandledRejectionHandler (E:\Rich2017\2018\project\weiwei\node_modules\egg\lib\egg.js:302:24)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:94:22)
    at process._tickCallback (internal/process/next_tick.js:189:7)
name: 'unhandledRejectionError'
pid: 15812
hostname: DELL-PC

2018-05-21 14:48:12,167 ERROR 12172 nodejs.unhandledRejectionError: [object Object]
    at Application._unhandledRejectionHandler (E:\Rich2017\2018\project\weiwei\node_modules\egg\lib\egg.js:302:24)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:94:22)
    at process._tickCallback (internal/process/next_tick.js:189:7)
name: 'unhandledRejectionError'
pid: 12172
hostname: DELL-PC

2018-05-21 16:02:32,611 ERROR 10216 nodejs.unhandledExceptionError: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TCP.onread (net.js:606:25)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 10216
hostname: DELL-PC

2018-05-21 16:02:35,338 ERROR 9460 [-/127.0.0.1/-/7ms POST /updateImg] nodejs.TypeError: Cannot read property 'body' of undefined
    at HomeController.updateImg (E:\Rich2017\2018\project\weiwei\app\controller\home.js:22:28)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at Object.classControllerMiddleware (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at wrappedController (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)
    at errorHandler (E:\Rich2017\2018\project\weiwei\app\middleware\error_handler.js:4:13)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)

pid: 9460
hostname: DELL-PC

2018-05-21 16:13:26,548 ERROR 10216 nodejs.unhandledExceptionError: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TCP.onread (net.js:606:25)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 10216
hostname: DELL-PC

2018-05-21 16:15:45,053 ERROR 13800 [-/127.0.0.1/-/14ms POST /updateImg] nodejs.ReferenceError: res is not defined
    at QiniuService.addImg (E:\Rich2017\2018\project\weiwei\app\service\qiniu.js:86:21)
    at HomeController.updateImg (E:\Rich2017\2018\project\weiwei\app\controller\home.js:24:29)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at Object.classControllerMiddleware (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at wrappedController (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)
    at errorHandler (E:\Rich2017\2018\project\weiwei\app\middleware\error_handler.js:4:13)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)

pid: 13800
hostname: DELL-PC

2018-05-21 16:18:09,047 ERROR 6436 nodejs.ENOENTError: ENOENT: no such file or directory, open 'E:\Rich2017\2018\project\weiwei\blob:http:\127.0.0.1:7001\f9e7f899-c52d-4030-a3ea-17d1b271085e' (uncaughtException throw 1 times on pid:6436)
ENOENTError: ENOENT: no such file or directory, open 'E:\Rich2017\2018\project\weiwei\blob:http:\127.0.0.1:7001\f9e7f899-c52d-4030-a3ea-17d1b271085e' (uncaughtException throw 1 times on pid:6436)
errno: -4058
code: 'ENOENT'
syscall: 'open'
path: 'E:\\Rich2017\\2018\\project\\weiwei\\blob:http:\\127.0.0.1:7001\\f9e7f899-c52d-4030-a3ea-17d1b271085e'
name: 'ENOENTError'
pid: 6436
hostname: DELL-PC

2018-05-21 16:18:09,062 ERROR 6436 [-/127.0.0.1/-/40ms POST /updateImg] nodejs.ENOENTError: ENOENT: no such file or directory, open 'E:\Rich2017\2018\project\weiwei\blob:http:\127.0.0.1:7001\f9e7f899-c52d-4030-a3ea-17d1b271085e' (uncaughtException throw 1 times on pid:6436)
ENOENTError: ENOENT: no such file or directory, open 'E:\Rich2017\2018\project\weiwei\blob:http:\127.0.0.1:7001\f9e7f899-c52d-4030-a3ea-17d1b271085e' (uncaughtException throw 1 times on pid:6436)
errno: -4058
code: 'ENOENT'
syscall: 'open'
path: 'E:\\Rich2017\\2018\\project\\weiwei\\blob:http:\\127.0.0.1:7001\\f9e7f899-c52d-4030-a3ea-17d1b271085e'
name: 'ENOENTError'
pid: 6436
hostname: DELL-PC

2018-05-21 16:29:38,630 ERROR 7184 nodejs.unhandledExceptionError: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TCP.onread (net.js:606:25)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 7184
hostname: DELL-PC

2018-05-21 16:37:50,689 ERROR 7184 nodejs.unhandledExceptionError: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TCP.onread (net.js:606:25)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 7184
hostname: DELL-PC

2018-05-21 16:59:20,951 ERROR 7184 nodejs.unhandledExceptionError: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TCP.onread (net.js:606:25)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 7184
hostname: DELL-PC

2018-05-21 17:15:31,944 ERROR 7184 nodejs.unhandledExceptionError: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TCP.onread (net.js:606:25)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 7184
hostname: DELL-PC

2018-05-22 09:58:36,228 ERROR 13436 [egg-mongoose] mongodb://localhost:27017/weiwei disconnected
2018-05-22 09:58:36,231 ERROR 13436 nodejs.MongoError: [egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (E:\Rich2017\2018\project\weiwei\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at emitOne (events.js:115:13)
    at Pool.emit (events.js:210:7)
    at Connection.<anonymous> (E:\Rich2017\2018\project\weiwei\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at Connection.emit (events.js:213:7)
    at Socket.<anonymous> (E:\Rich2017\2018\project\weiwei\node_modules\mongodb-core\lib\connection\connection.js:189:49)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
name: 'MongoError'
message: '[egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]'
pid: 13436
hostname: DELL-PC

2018-05-22 10:06:02,094 ERROR 16216 [-/127.0.0.1/-/1ms GET /pages] nodejs.TypeError: Cannot read property 'find' of undefined
    at HomeController.fetchPage (E:\Rich2017\2018\project\weiwei\app\controller\home.js:32:26)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at Object.classControllerMiddleware (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at wrappedController (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)
    at errorHandler (E:\Rich2017\2018\project\weiwei\app\middleware\error_handler.js:4:13)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)

pid: 16216
hostname: DELL-PC

2018-05-22 10:06:24,552 ERROR 13648 [-/127.0.0.1/-/2ms GET /pages] nodejs.TypeError: Cannot read property 'find' of undefined
    at HomeController.fetchPage (E:\Rich2017\2018\project\weiwei\app\controller\home.js:32:26)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at Object.classControllerMiddleware (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at wrappedController (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)
    at errorHandler (E:\Rich2017\2018\project\weiwei\app\middleware\error_handler.js:4:13)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)

pid: 13648
hostname: DELL-PC

2018-05-22 10:06:30,425 ERROR 12112 [-/127.0.0.1/-/2ms GET /pages] nodejs.TypeError: Cannot read property 'find' of undefined
    at HomeController.fetchPage (E:\Rich2017\2018\project\weiwei\app\controller\home.js:32:26)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at Object.classControllerMiddleware (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at wrappedController (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)
    at errorHandler (E:\Rich2017\2018\project\weiwei\app\middleware\error_handler.js:4:13)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)

pid: 12112
hostname: DELL-PC

2018-05-22 10:06:54,217 ERROR 8832 [-/127.0.0.1/-/1ms GET /pages] nodejs.TypeError: Cannot read property 'find' of undefined
    at HomeController.fetchPage (E:\Rich2017\2018\project\weiwei\app\controller\home.js:32:26)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at Object.classControllerMiddleware (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at wrappedController (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)
    at errorHandler (E:\Rich2017\2018\project\weiwei\app\middleware\error_handler.js:4:13)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)

pid: 8832
hostname: DELL-PC

2018-05-22 10:07:38,532 ERROR 8832 [-/127.0.0.1/-/0ms GET /pages] nodejs.TypeError: Cannot read property 'find' of undefined
    at HomeController.fetchPage (E:\Rich2017\2018\project\weiwei\app\controller\home.js:32:26)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at Object.classControllerMiddleware (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at wrappedController (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)
    at errorHandler (E:\Rich2017\2018\project\weiwei\app\middleware\error_handler.js:4:13)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)

pid: 8832
hostname: DELL-PC

2018-05-22 10:08:13,320 ERROR 13356 [-/127.0.0.1/-/1ms GET /getPages] nodejs.TypeError: Cannot read property 'find' of undefined
    at HomeController.fetchPage (E:\Rich2017\2018\project\weiwei\app\controller\home.js:32:26)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at Object.classControllerMiddleware (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at wrappedController (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)
    at errorHandler (E:\Rich2017\2018\project\weiwei\app\middleware\error_handler.js:4:13)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)

pid: 13356
hostname: DELL-PC

2018-05-22 10:08:14,140 ERROR 13356 [-/127.0.0.1/-/1ms GET /getPages] nodejs.TypeError: Cannot read property 'find' of undefined
    at HomeController.fetchPage (E:\Rich2017\2018\project\weiwei\app\controller\home.js:32:26)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at Object.classControllerMiddleware (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at wrappedController (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)
    at errorHandler (E:\Rich2017\2018\project\weiwei\app\middleware\error_handler.js:4:13)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)

pid: 13356
hostname: DELL-PC

2018-05-22 10:08:37,826 ERROR 13356 [-/127.0.0.1/-/0ms GET /getPages] nodejs.TypeError: Cannot read property 'find' of undefined
    at HomeController.fetchPage (E:\Rich2017\2018\project\weiwei\app\controller\home.js:32:26)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at Object.classControllerMiddleware (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\index.js:36:21)
    at wrappedController (E:\Rich2017\2018\project\weiwei\node_modules\egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\Rich2017\2018\project\weiwei\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)
    at errorHandler (E:\Rich2017\2018\project\weiwei\app\middleware\error_handler.js:4:13)
    at dispatch (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:42:32)
    at next (E:\Rich2017\2018\project\weiwei\node_modules\koa-compose\index.js:43:18)

pid: 13356
hostname: DELL-PC

2018-05-22 10:24:20,691 ERROR 13572 [-/127.0.0.1/-/4ms GET /getPages?size=100] nodejs.MongoError: Failed to parse: { find: "t_wei_pages", filter: {}, projection: {}, limit: "100" }. 'limit' field must be numeric.
    at Function.MongoError.create (E:\Rich2017\2018\project\weiwei\node_modules\mongodb-core\lib\error.js:31:11)
    at queryCallback (E:\Rich2017\2018\project\weiwei\node_modules\mongodb-core\lib\cursor.js:212:36)
    at E:\Rich2017\2018\project\weiwei\node_modules\mongodb-core\lib\connection\pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
name: 'MongoError'
message: 'Failed to parse: { find: "t_wei_pages", filter: {}, projection: {}, limit: "100" }. \'limit\' field must be numeric.'
waitedMS: 0
ok: 0
errmsg: 'Failed to parse: { find: "t_wei_pages", filter: {}, projection: {}, limit: "100" }. \'limit\' field must be numeric.'
code: 9
pid: 13572
hostname: DELL-PC

